version: 0.2


# Steps:
#   Checkout
#   Install dependencies
#   Run unit-tests
#   Static code analysis - linting
#   Security - dependency vulnerability scaner

# Note: SNYK_TOKEN env var is needed

phases:
  install:
    commands:
      - npm install -g snyk
  build:
    commands:
      - echo "STAGE - install dependencies"
      - pip install -r requirements.txt

      - echo "STAGE - run unit-tests"
      - python HelloWorldTests.py

      - echo "STAGE - static code analysis - linting"
      - pycodestyle --show-source --show-pep8 ./HelloWorld.py

      - echo "STAGE - security - dependency vulnerability scaner"
      - snyk test
  post_build:
    commands:
      - echo "COMPLETE"
